import type { Dict, Service } from "./de";

export const nl: Dict = {
  common: {
    cta: "Project starten",
    ctaSecondary: "Diensten bekijken",
    learnMore: "Meer informatie",
    from: "vanaf",
    workdays: "werkdagen",
    workday: "werkdag",
    netPerDay: "€ 999 netto / werkdag",
    allServices: "Alle diensten",
  },
  home: {
    badge: "AI-ondersteunde ontwikkeling · Deutsch & Nederlands · B2B",
    titleA: "Digitale excellentie.",
    titleB: "In dagen in plaats van maanden.",
    subtitle:
      "NeXify AI ontwikkelt premium websites, webshops, web-apps en AI-automatiseringen – persoonlijk verantwoord door één vakman, versneld door de modernste AI-tools, transparant tegen een vast dagtarief van € 999 netto.",
    ctaPrimary: "Gratis adviesgesprek",
    ctaSecondary: "Diensten ontdekken",
    stats: [
      { value: "€ 999", label: "netto per werkdag – geen verborgen kosten" },
      { value: "1–3", label: "dagen tot een complete website" },
      { value: "100 %", label: "persoonlijke verantwoordelijkheid, geen overdrachtsketens" },
      { value: "24/7", label: "NeXify AI adviseur voor uw vraag" },
    ],
    pillarsEyebrow: "Waarom NeXify AI",
    pillarsTitle: "Eén vakman. Moderne AI. Meetbare resultaten.",
    pillars: [
      {
        icon: "Code2",
        title: "Eén vakman, één resultaat",
        text: "Geen overdrachtsketen tussen sales, design, ontwikkeling en QA. Concept, architectuur, uitvoering en kwaliteitscontrole liggen in één hand – persoonlijk en transparant.",
      },
      {
        icon: "Bot",
        title: "AI-ondersteund, niet AI-uitbesteed",
        text: "De modernste AI-tools verkorten onderzoek, uitvoering en controle drastisch. De vakinhoudelijke beslissingen neemt nog altijd een ervaren ontwikkelaar – met volledige verantwoordelijkheid.",
      },
      {
        icon: "ChartNoAxesCombined",
        title: "Transparantie per werkdag",
        text: "€ 999 netto per werkdag. Omvang, aannames en meerwerk worden vóór de uitvoering zichtbaar gemaakt – u houdt altijd volledige kostencontrole.",
      },
    ],
    servicesEyebrow: "Diensten",
    servicesTitle: "Van de eerste klik tot een geschaald platform",
    servicesText: "Acht helder gedefinieerde bouwstenen – elk met een vaste doorlooptijd, duidelijke resultaten en een transparante prijs.",
    processEyebrow: "Werkwijze",
    processTitle: "Vijf stappen. Nul verrassingen.",
    quotesEyebrow: "Stemmen & resultaten",
    quotesTitle: "Wat samenwerken met NeXify AI betekent",
    ctaBandTitle: "Klaar voor uw project?",
    ctaBandText:
      "Beschrijf uw plan – u ontvangt binnen één werkdag een eerlijke inschatting met urenraming en prijsindicatie. Of vraag het direct aan NeXify AI, onze AI-adviseur in de chat.",
    ctaBandBtn: "Aanvraag versturen",
    ctaBandBtn2: "Chat met NeXify AI",
    marquee: ["Next.js", "React", "TypeScript", "Supabase", "AI-agenten", "Automatisering", "E-commerce", "Web-apps", "Mobile apps", "SEO", "Cloud-infrastructuur", "API-integratie"],
  },
  services: [
    {
      slug: "landingpages",
      icon: "LayoutTemplate",
      title: "Landingspagina's die begrijpelijk verkopen",
      shortTitle: "Landingspagina",
      eyebrow: "Helder. Snel. Conversiegericht.",
      description:
        "Eén gefocuste pagina voor een aanbod, campagne of marktintroductie – bedacht, ontworpen, ontwikkeld en technisch netjes opgeleverd. Van de eerste wireframe tot livegang ontstaat een pagina die bezoekers begrijpt, leidt en converteert.",
      promise: "Een verkoopklare landingspagina in één werkdag.",
      days: "1 werkdag",
      minDays: 1,
      maxDays: 1,
      features: ["Premium UI/UX in huisstijl", "Responsive op alle apparaten", "Contact- of leadformulier", "Technische SEO & metadata", "Performance-optimalisatie (Core Web Vitals)", "Wettelijk verplichte links"],
      deliverables: ["Strategische paginastructuur", "Individueel premium design", "Next.js-implementatie", "Formulierintegratie met e-mailkoppeling", "QA op desktop en mobiel"],
      idealFor: ["Nieuwe proposities", "Campagnes", "Leadgeneratie", "Productvalidatie"],
    },
    {
      slug: "websites",
      icon: "Globe2",
      title: "Bedrijfswebsites met inhoud",
      shortTitle: "Bedrijfswebsite",
      eyebrow: "Merk, vertrouwen en vraag in één systeem.",
      description:
        "Een complete B2B-bedrijfswebsite met heldere positionering, dienstenpagina's, contactflow, SEO-basis en alle vereiste standaardpagina's. Strategie, content en techniek worden samen bedacht – voor een website die aanvragen oplevert in plaats van alleen te bestaan.",
      promise: "Een complete website in twee tot drie werkdagen.",
      days: "2–3 werkdagen",
      minDays: 2,
      maxDays: 3,
      features: ["Strategie en informatiearchitectuur", "Home- en dienstenpagina's", "Over-ons-/expertprofiel", "Prijs- en procespresentatie", "Contactflow met formulier", "Juridische pagina's (colofon, privacy, voorwaarden)"],
      deliverables: ["Next.js App Router architectuur", "Individueel designsysteem", "SEO-metadata en sitemap", "Responsive QA", "Deployment-voorbereiding"],
      idealFor: ["Bureaus", "Adviesbedrijven", "Vakbedrijven en mkb", "B2B-dienstverleners"],
    },
    {
      slug: "onlineshops",
      icon: "ShoppingCart",
      title: "Webshops die met het assortiment meegroeien",
      shortTitle: "Webshop",
      eyebrow: "Snel bestellen. Schone data. Duidelijke processen.",
      description:
        "Van een gefocuste shop tot een uitgebreid handelssysteem: productzoeken, categorieën, checkout, betalingen, voorraadbeheer en automatiseringen worden passend bij uw bedrijf gepland. Niet de bouwdoos bepaalt de shop – uw businessmodel doet dat.",
      promise: "Standaardshops in zes tot acht dagen, grote catalogi vanaf twaalf dagen.",
      days: "6–8 werkdagen",
      minDays: 6,
      maxDays: 8,
      features: ["Product- en categoriestructuur", "Zoeken en filters", "Checkout en betaalproviders", "Ordercommunicatie per e-mail", "SEO en gestructureerde data", "Koppelingen en productimport"],
      deliverables: ["Shop-frontend", "Beheerlogica", "Productimport", "Checkout-tests", "Beheer- en overdrachtsdocumentatie"],
      idealFor: ["D2C en B2B-commerce", "Nichehandel", "Fabrikanten", "Assortimenten tot circa 50.000 artikelen"],
    },
    {
      slug: "enterprise-commerce",
      icon: "Boxes",
      title: "Commerce-platforms vanaf 50.000 artikelen",
      shortTitle: "Enterprise-commerce",
      eyebrow: "Catalogi, zoeken, integraties en beheer voor grote datavolumes.",
      description:
        "Voor grote assortimenten worden datamodel, zoekindex, importpipeline, caching, productvarianten, ERP/PIM-koppeling en monitoring vanaf het begin schaalbaar opgezet. Performance en datakwaliteit zijn hier geen achteraf-oplossing, maar architectuurprincipe.",
      promise: "Grote shops starten vanaf twaalf werkdagen – de omvang volgt de werkelijke systeemcomplexiteit.",
      days: "vanaf 12 werkdagen",
      minDays: 12,
      from: true,
      features: ["50.000+ artikelen performant", "Snelle zoekfunctie met facetten", "PIM-/ERP-/feed-integratie", "Batch- en delta-imports", "Cache- en indexstrategie", "Monitoring en recovery"],
      deliverables: ["Technische blueprint", "Import- en zoekarchitectuur", "Schaalbare shop", "Load- en datakwaliteitstests", "Beheerhandboek"],
      idealFor: ["Groothandel", "Onderdelenhandel", "Multi-merkshops", "Catalogusgedreven platforms"],
    },
    {
      slug: "web-apps",
      icon: "AppWindow",
      title: "Web-apps voor echte bedrijfsprocessen",
      shortTitle: "Web-app",
      eyebrow: "Portalen, dashboards en processoftware.",
      description:
        "Individuele webapplicaties voor klantportalen, interne processen, boekingen, planning, documenten, workflows of branchespecifieke processen. Software die zich aanpast aan uw bedrijf – niet andersom.",
      promise: "Compacte MVP's in zes tot acht dagen, complexe systemen vanaf twaalf dagen.",
      days: "6–8 werkdagen",
      minDays: 6,
      maxDays: 8,
      features: ["Login en rollenconcept", "Dashboards en rapportages", "Datamodellen en API's", "Workflows en notificaties", "Bestands- en documentbeheer", "Auditeerbare statussen"],
      deliverables: ["Productconcept", "Responsive web-app", "Backend/API", "Tests", "Deployment- en beheeroverdracht"],
      idealFor: ["Klantportalen", "SaaS-MVP's", "Interne tools", "Boekings- en serviceplatforms"],
    },
    {
      slug: "mobile-apps",
      icon: "Smartphone",
      title: "Mobiele apps met gedeelde productkern",
      shortTitle: "Mobiele app",
      eyebrow: "Cross-platform, onderhoudbaar en gefocust op de use case.",
      description:
        "Mobiele applicaties worden als gefocuste producten ontwikkeld – met een gedeeld designsysteem voor iOS en Android, nette API-koppeling en een duidelijke publicatiestrategie in de stores.",
      promise: "Compacte cross-platform MVP's in zes tot acht dagen, uitgebreide apps vanaf twaalf dagen.",
      days: "6–8 werkdagen",
      minDays: 6,
      maxDays: 8,
      features: ["iOS en Android uit één codebase", "Cross-platform architectuur", "Authenticatie", "Push en notificaties", "Offline-/sync-concept", "Store-voorbereiding"],
      deliverables: ["Productflow", "App-interface", "API-integratie", "Apparaattests", "Release-checklist"],
      idealFor: ["Service-apps", "Buitendienst", "Klantloyaliteit", "Mobiele procesondersteuning"],
    },
    {
      slug: "automatisierung",
      icon: "Workflow",
      title: "AI-ondersteunde automatisering met controle",
      shortTitle: "Automatisering",
      eyebrow: "Minder routine. Meer controleerbaar beheer.",
      description:
        "Terugkerende taken worden geanalyseerd, gestandaardiseerd en met passende workflows, integraties en AI-ondersteunde stappen geautomatiseerd. Elk geautomatiseerd proces blijft meetbaar, gedocumenteerd en controleerbaar.",
      promise: "Niet zoveel mogelijk automatiseren – maar het juiste, meetbaar en gecontroleerd.",
      days: "vanaf 1 werkdag",
      minDays: 1,
      from: true,
      features: ["Procesanalyse", "E-mail- en documentflows", "CRM-/ERP-integraties", "Goedkeuringen en policy-gates", "Monitoring", "Fout- en recovery-paden"],
      deliverables: ["Proceskaart", "Geautomatiseerde workflow", "Testcases", "Monitoring", "Beheerdocumentatie"],
      idealFor: ["Sales", "Support", "Backoffice", "Project- en dataprocessen"],
    },
    {
      slug: "ai-agenten",
      icon: "Bot",
      title: "AI-agenten voor duidelijk afgebakende taken",
      shortTitle: "AI-agenten",
      eyebrow: "Tools, regels en bewijsvoering in plaats van ongecontroleerde chatbots.",
      description:
        "Agent-oplossingen krijgen eenduidige rollen, datatoegang, goedkeuringen, tests en logging. Zo ontstaan betrouwbare assistenten en operators in plaats van demo-chats – zoals NeXify AI, de AI-adviseur op deze website.",
      promise: "AI ondersteunt het werk – vakinhoudelijke verantwoordelijkheid, grenzen en controle blijven zichtbaar.",
      days: "vanaf 3 werkdagen",
      minDays: 3,
      from: true,
      features: ["Rollen en rechten", "Kennistoegang (RAG)", "Tool- en API-koppeling", "Goedkeuringsniveaus", "Evaluatie", "Evidence en monitoring"],
      deliverables: ["Agentprofiel", "Tool- en kenniskoppeling", "Veiligheidsregels", "Testsuite", "Beheerconcept"],
      idealFor: ["Kenniswerk", "Support", "Research", "Interne operations"],
    },
  ] as Service[],
  servicesPage: {
    eyebrow: "Diensten",
    title: "Acht bouwstenen. Eén ambitie: excellentie.",
    intro:
      "Elke dienst heeft een duidelijke doorlooptijd, gedefinieerde resultaten en een transparante prijs van € 999 netto per werkdag. Wat u hier leest, krijgt u – zonder kleine lettertjes, zonder bureau-overhead.",
    featuresLabel: "Omvang",
    deliverablesLabel: "U ontvangt",
    idealLabel: "Ideaal voor",
  },
  pricing: {
    eyebrow: "Prijzen",
    title: "Eén tarief. Volledige transparantie.",
    intro:
      "€ 999 netto per werkdag – dit tarief geldt voor elke dienst, elk project, elke dag. Een werkdag omvat maximaal acht planbare vakuren voor concept, design, ontwikkeling, tests en documentatie.",
    dayRateTitle: "Het dagtarief",
    dayRateText:
      "Vóór projectstart ontvangt u een betrouwbare urenraming in werkdagen. Een bindende totaalprijs is mogelijk zodra omvang, content, integraties en acceptatiecriteria eenduidig vaststaan. Meerwerk wordt altijd vóór uitvoering gemeld – nooit achteraf.",
    includedTitle: "Inbegrepen in de werkdag",
    included: [
      "Concept en informatiearchitectuur",
      "Individueel design binnen het designsysteem",
      "Ontwikkeling (frontend, backend, API's)",
      "Integraties en datakoppelingen",
      "Tests, QA en mobiele controle",
      "Documentatie en overdracht",
    ],
    notIncludedTitle: "Niet inbegrepen (tenzij overeengekomen)",
    notIncluded: ["Hosting- en domeinkosten", "Licenties en externe API-kosten", "Kosten van betaalproviders", "Stockmateriaal en contentcreatie", "Doorlopende onderhoudscontracten (apart te boeken)"],
    calcTitle: "Projectkosten-calculator",
    calcText: "Kies een dienst en de verwachte omvang – u ziet direct de realistische investering.",
    calcService: "Dienst",
    calcDays: "Werkdagen",
    calcNet: "Netto-investering",
    calcVat: "excl. 21 % btw",
    calcGross: "Bruto (incl. btw)",
    calcNote: "Bij grensoverschrijdende B2B-diensten binnen de EU kan met een geldig btw-nummer de verleggingsregeling gelden – dan wordt geen btw berekend.",
    vatNote: "Alle prijzen netto excl. toepasselijke btw. Uitsluitend B2B.",
  },
  process: {
    eyebrow: "Werkwijze",
    title: "Vijf stappen van idee naar livegang",
    intro:
      "Een gestandaardiseerd, honderdvoudig verfijnd proces zorgt ervoor dat projecten in dagen in plaats van maanden klaar zijn – zonder kwaliteitsverlies, zonder verrassingen, met volledige transparantie in elke stap.",
    steps: [
      { n: "01", icon: "ChartNoAxesCombined", title: "Doel en bedrijfswaarde", text: "We bepalen welk resultaat telt, wie het gebruikt en wat bewust géén deel uitmaakt van de eerste scope. Focus verslaat de feature-lijst." },
      { n: "02", icon: "MessageSquareMore", title: "Concept en prijsindicatie", text: "De inspanning wordt in werkdagen uitgedrukt. U ziet vooraf scope, prijsindicatie, aannames en mogelijke uitbreidingen – schriftelijk en betrouwbaar." },
      { n: "03", icon: "Code2", title: "AI-ondersteunde uitvoering", text: "Moderne ontwikkel- en controletools versnellen analyse, design, code, tests en documentatie – onder permanente vakinhoudelijke leiding." },
      { n: "04", icon: "Settings2", title: "Tests en acceptatie", text: "Functionaliteit, weergave, mobiele weergave, formulieren, performance en centrale gebruikersflows worden aantoonbaar getest en gedocumenteerd." },
      { n: "05", icon: "Rocket", title: "Overdracht en doorontwikkeling", text: "U ontvangt code, documentatie, duidelijke beheerinformatie en een geprioriteerde lijst met zinvolle vervolgstappen." },
    ],
    promiseTitle: "Waar u op kunt rekenen",
    promises: [
      { title: "Antwoord binnen 24 uur", text: "Elke aanvraag krijgt binnen één werkdag een persoonlijk, gekwalificeerd antwoord." },
      { title: "Schriftelijke scope-duidelijkheid", text: "Geen project start zonder gedocumenteerde omvang, aannames en prijsindicatie." },
      { title: "Dagelijkse zichtbaarheid", text: "Bij meerdaagse projecten ziet u de voortgang – niet pas aan het einde." },
      { title: "Nette overdracht", text: "Code, toegangen, documentatie en beheerinstructies zijn van u. Geen vendor lock-in." },
    ],
  },
  platform: {
    eyebrow: "Platform & technologie",
    title: "De techstack achter de snelheid",
    intro:
      "Snelheid zonder kwaliteitsverlies ontstaat door een bewust samengestelde, honderdvoudig beproefde technologiestack – gecombineerd met AI-ondersteunde ontwikkel- en controletools van de nieuwste generatie.",
    blocks: [
      {
        icon: "Layers",
        title: "Frontend & design",
        text: "Moderne, onderhoudbare interfaces met uitstekende performance en toegankelijkheid.",
        points: ["Next.js App Router & React", "TypeScript overal", "Individuele designsystemen", "Core Web Vitals geoptimaliseerd", "Responsive & toegankelijk"],
      },
      {
        icon: "Database",
        title: "Backend & data",
        text: "Schaalbare API's en datamodellen die met uw bedrijf meegroeien.",
        points: ["Supabase / PostgreSQL", "REST- & streaming-API's", "Authenticatie & rollen", "Data-importpipelines", "Back-ups & monitoring"],
      },
      {
        icon: "Bot",
        title: "AI & agenten",
        text: "Productierijpe AI-integraties met controle, logging en goedkeuringen.",
        points: ["GPT-, Claude- & Gemini-integratie", "RAG-kenniskoppeling", "AI-adviseurs zoals NeXify AI", "Offerte- & e-mailautomatisering", "Evaluatie & guardrails"],
      },
      {
        icon: "ShieldCheck",
        title: "Beheer & veiligheid",
        text: "Betrouwbaar beheer met duidelijke verantwoordelijkheden en AVG-conformiteit.",
        points: ["Vercel & self-hosting (Docker/Traefik)", "Cloudflare CDN & bescherming", "SSL, security-headers, hardening", "AVG-conforme datastromen", "Transactionele e-mails (Resend)"],
      },
    ],
    novaTitle: "NeXify AI – uw AI-adviseur op deze website",
    novaText:
      "Wat u rechtsonder in de chat ervaart, is een voorbeeld van onze AI-agent-dienst: NeXify AI adviseert bezoekers in twee talen, kwalificeert aanvragen, stelt gestructureerde offertes op en verstuurt ze automatisch per e-mail – inclusief opvolging. Dezelfde technologie bouwen wij voor uw bedrijf.",
    novaBtn: "NeXify AI nu testen",
  },
  references: {
    eyebrow: "Referenties & resultaten",
    title: "Resultaten die voor zich spreken",
    intro:
      "Geselecteerde, geanonimiseerde projectresultaten uit web, commerce en automatisering. Op verzoek brengen wij u graag in contact met passende referenties.",
    cases: [
      {
        tag: "B2B-website",
        title: "Adviesbureau, DACH",
        text: "Complete bedrijfswebsite met dienstenarchitectuur, SEO-basis en contactflow – bedacht en live in drie werkdagen.",
        results: ["3 werkdagen tot livegang", "+68 % organische aanvragen in 90 dagen", "Laadtijd onder 1 seconde"],
      },
      {
        tag: "E-commerce",
        title: "Onderdelenhandel, Nederland",
        text: "Commerce-platform met 60.000+ artikelen, gefacetteerd zoeken, ERP-koppeling en geautomatiseerde delta-imports.",
        results: ["60.000+ artikelen performant", "Zoekresultaten onder 150 ms", "Importrun volautomatisch, dagelijks"],
      },
      {
        tag: "AI-automatisering",
        title: "Mkb-dienstverlener",
        text: "Geautomatiseerde offerte- en e-mailflow met AI-voorkwalificatie van binnenkomende aanvragen en CRM-integratie.",
        results: ["–70 % handmatige verwerkingstijd", "Reactietijd van 2 dagen naar 2 uur", "Volledig gelogde workflow"],
      },
    ],
    quotes: [
      {
        quote: "Binnen drie dagen stond er een website waarvoor bureaus ons drie maanden hadden geoffreerd – in betere kwaliteit en voor een fractie van de prijs.",
        author: "Directeur, adviesbureau (DACH)",
      },
      {
        quote: "De combinatie van persoonlijke verantwoordelijkheid en AI-snelheid is indrukwekkend. Elke toezegging werd nagekomen, elke inspanning vooraf transparant gemaakt.",
        author: "Eigenaar, handelsonderneming (NL)",
      },
      {
        quote: "Eindelijk iemand die automatisering niet als buzzword verkoopt, maar als gecontroleerd, meetbaar proces realiseert.",
        author: "Operations-manager, dienstverlener (DE)",
      },
    ],
  },
  wissen: {
    eyebrow: "Kennis",
    title: "Inzichten in AI-ondersteunde ontwikkeling",
    intro: "Praktijkgerichte kennis over websites, commerce, automatisering en AI-agenten – zonder marketingmist, mét duidelijke aanbevelingen.",
    readMore: "Verder lezen",
    readLess: "Inklappen",
    articles: [
      {
        tag: "Strategie",
        readTime: "4 min.",
        title: "Waarom een website in 3 dagen beter kan zijn dan één in 3 maanden",
        excerpt: "Lange doorlooptijden ontstaan zelden door kwaliteit – meestal door overdrachten, afstemmingsrondes en stilstand.",
        body: [
          "Het klassieke bureauproces kent veel stations: sales, strategie, design, ontwikkeling, QA, projectmanagement. Elke overdracht kost tijd, informatie en geld. Het resultaat wordt er niet beter van – alleen duurder en later.",
          "AI-ondersteunde ontwikkeling draait het model om: één ervaren vakman stuurt het hele proces en gebruikt AI-tools voor onderzoek, code, tests en documentatie. De doorlooptijd daalt van maanden naar dagen, terwijl de kwaliteitscontrole in één hand blijft.",
          "Doorslaggevend is standaardisatie: beproefde architecturen, herbruikbare designsystemen en geautomatiseerde controles. Wie elke stap voor de honderdste keer zet, zet hem sneller en veiliger.",
        ],
      },
      {
        tag: "E-commerce",
        readTime: "5 min.",
        title: "50.000 artikelen zijn geen frontend-probleem – maar een dataprobleem",
        excerpt: "Grote catalogi falen zelden op uiterlijk. Ze falen op imports, zoeken en datakwaliteit.",
        body: [
          "Wie een shop met grote assortimenten plant, moet eerst over datastromen praten: waar komen artikelstamgegevens vandaan? Hoe vaak wijzigen prijzen en voorraden? Welke systemen (ERP, PIM, leveranciersfeeds) moeten worden gekoppeld?",
          "Het antwoord bepaalt de architectuur: batch- en delta-imports, een performante zoekindex met facetten, consequente caching en monitoring die datafouten opmerkt vóórdat klanten ze zien.",
          "Een shop die deze basis vanaf het begin meedenkt, schaalt moeiteloos van 5.000 naar 100.000 artikelen. Eén die het moet inbouwen, wordt een permanent project.",
        ],
      },
      {
        tag: "AI-agenten",
        readTime: "6 min.",
        title: "Van chatbot naar salesagent: wat NeXify AI anders doet",
        excerpt: "De meeste website-chatbots beantwoorden FAQ's. Een echte AI-agent kwalificeert, adviseert en stelt offertes op.",
        body: [
          "Een klassieke chatbot is een zoekvenster met een tekstballon. Een AI-agent daarentegen heeft een rol, een doel en tools: hij kent het dienstenportfolio, rekent prijzen transparant voor, stelt kwalificatievragen en stelt uiteindelijk een gestructureerde offerte op.",
          "NeXify AI – de adviseur op deze website – toont het principe live: het gesprek wordt opgeslagen, de offerte per e-mail verzonden, en na 24 uur volgt automatisch een vriendelijke opvolging. Van een anonieme bezoeker wordt een gedocumenteerde lead.",
          "Belangrijk zijn de vangrails: geen verzonnen toezeggingen, duidelijke prijslogica, logging van elke interactie. AI in sales werkt alleen met controle – maar dan buitengewoon goed.",
        ],
      },
      {
        tag: "Automatisering",
        readTime: "4 min.",
        title: "De juiste volgorde van automatiseren",
        excerpt: "Niet alles wat geautomatiseerd kán worden, moet geautomatiseerd worden. Een prioriteringshulp.",
        body: [
          "Het beste startpunt zijn processen die frequent, regelgebaseerd en vervelend zijn: offertedocumenten, e-mailrouting, dataoverdracht tussen systemen, rapportages. Hier is het rendement direct meetbaar.",
          "Daarna volgen processen met AI-ondersteuning: voorkwalificatie van aanvragen, samenvattingen, conceptteksten. Hier blijft een mens in de goedkeuring – de AI versnelt, maar beslist niet alleen.",
          "Als laatste komen complexe agent-workflows. Wie de eerste twee stappen netjes heeft gebouwd, beschikt over de datakwaliteit en procesduidelijkheid die stap drie pas mogelijk maken.",
        ],
      },
      {
        tag: "Technologie",
        readTime: "5 min.",
        title: "Next.js, Supabase & co.: waarom deze stack",
        excerpt: "Technologiekeuzes zijn beheerkostenkeuzes. Een onderbouwing van de NeXify-stack.",
        body: [
          "Next.js levert server-rendering, uitstekende SEO en een ecosysteem dat van start-ups tot concerns wordt gedragen. React en TypeScript borgen onderhoudbaarheid en ontwikkelaarsbeschikbaarheid voor jaren.",
          "Supabase combineert PostgreSQL – de betrouwbaarste open-source database – met authenticatie, storage en realtime-functies. Dat reduceert integratiewerk drastisch, zonder in proprietary afhankelijkheid te belanden.",
          "Het principe: technologie volgt het bedrijf. Elke component moet vervangbaar blijven, data moet exporteerbaar zijn, en de klant ontvangt altijd de volledige code.",
        ],
      },
      {
        tag: "Recht & compliance",
        readTime: "5 min.",
        title: "AVG-conforme AI-integratie: de checklist",
        excerpt: "AI-functies en privacy sluiten elkaar niet uit – als de basis klopt.",
        body: [
          "Ten eerste: dataminimalisatie. Aan AI-diensten wordt alleen doorgegeven wat voor het doel noodzakelijk is. Persoonsgegevens worden waar mogelijk gepseudonimiseerd of geheel vermeden.",
          "Ten tweede: transparantie. Gebruikers weten wanneer ze met een AI-systeem communiceren, wat wordt opgeslagen en waarvoor. Deze website doet dat voor met de AI-verklaring en de privacyverklaring.",
          "Ten derde: verwerkersovereenkomsten en opslaglocaties. Verwerkers worden contractueel gebonden, doorgiften naar derde landen getoetst, bewaartermijnen gedefinieerd. Wie dat documenteert, integreert AI rechtszeker.",
        ],
      },
    ],
  },
  faqPage: {
    eyebrow: "FAQ",
    title: "Veelgestelde vragen, eerlijke antwoorden",
    intro: "Alles over werkwijze, prijzen, AI-inzet en samenwerking – compact beantwoord. Mist u een vraag? de NeXify AI chat of het contactformulier helpen direct.",
  },
  faqs: [
    {
      q: "Hoe kan een complete website in twee tot drie dagen ontstaan?",
      a: "Niet door kwaliteit weg te laten, maar door een gestandaardiseerd proces, herbruikbare technische fundamenten, een consistent designsysteem en AI-ondersteunde analyse-, ontwikkel- en controleprocessen. Pascal Courbois verenigt concept, architectuur, uitvoering en kwaliteitscontrole persoonlijk.",
    },
    {
      q: "Welke rol speelt AI in de ontwikkeling?",
      a: "NeXify werkt AI-ondersteund. Moderne tools ondersteunen onderzoek, structurering, codecreatie, tests en documentatie. Vakinhoudelijke beslissingen, verantwoordelijkheid, controle en goedkeuring blijven bij de ervaren ontwikkelaar.",
    },
    {
      q: "Is € 999 per werkdag een vaste prijs?",
      a: "Het dagtarief staat vast. Vóór de start ontvangt u een betrouwbare urenraming. Een bindende totaalprijs is mogelijk zodra omvang, content, integraties en acceptatiecriteria eenduidig vaststaan.",
    },
    {
      q: "Wat is inbegrepen in een werkdag?",
      a: "Maximaal acht planbare vakuren voor concept, designsysteem, ontwikkeling, integratie, tests en documentatie. Externe kosten zoals hosting, domeinen, betaalproviders, licenties, content of stockmateriaal zijn niet inbegrepen, tenzij uitdrukkelijk overeengekomen.",
    },
    {
      q: "Waarom is de totaalprijs ondanks vakman-niveau zo laag?",
      a: "Omdat er niet meerdere afdelingen, overdrachten en lange bureauketens worden betaald. Eén ervaren aanspreekpunt stuurt het hele proces en gebruikt hypermoderne AI-tools, automatisering en beproefde open-source componenten om de doorlooptijd sterk te verkorten.",
    },
    {
      q: "Geldt altijd 21 procent btw?",
      a: "De website toont het Nederlandse standaardtarief van 21 procent als transparante vergelijking. Bij grensoverschrijdende B2B-diensten binnen de EU kan met een geldig btw-nummer de verleggingsregeling gelden. Bepalend zijn factuurontvanger, plaats van dienst en fiscale voorwaarden.",
    },
    {
      q: "Werkt NeXify uitsluitend voor bedrijven?",
      a: "Ja. Aanbiedingen en contracten richten zich uitsluitend op ondernemers, rechtspersonen en vergelijkbare beroepsmatig handelende organisaties.",
    },
    {
      q: "Welke technologieën worden ingezet?",
      a: "Afhankelijk van het doel onder andere Next.js, React, TypeScript, Supabase/PostgreSQL, moderne API's, Vercel of passende self-hosting infrastructuur. Technologie volgt het bedrijf – niet andersom.",
    },
    {
      q: "Wat kan de NeXify AI adviseur?",
      a: "NeXify AI is de AI-salesagent van deze website. Hij adviseert in het Duits en Nederlands, kwalificeert aanvragen, stelt gestructureerde vrijblijvende offertes op en verstuurt ze per e-mail – inclusief automatische opvolging. Dezelfde technologie bouwen wij ook voor uw bedrijf.",
    },
    {
      q: "Hoe gaat de samenwerking na de livegang verder?",
      a: "U ontvangt code, documentatie en beheerinstructies volledig overgedragen. Op verzoek verzorgen wij doorontwikkeling, onderhoud en monitoring tegen hetzelfde transparante dagtarief – zonder binding, zonder minimale looptijd.",
    },
  ],
  about: {
    eyebrow: "Over mij",
    title: "Pascal Courbois – de vakman achter NeXify AI",
    intro: "Duitser uit de grensregio Limburg, sinds ruim vijf jaar thuis in Nederland – met meer dan 20 jaar beroeps- en praktijkervaring in IT, commercie en sales. Eén aanspreekpunt voor strategie, design, ontwikkeling en beheer.",
    paragraphs: [
      "Ik ben Pascal Courbois – Duitser uit de grensregio Limburg, getrouwd met een Nederlandse en sinds ruim vijf jaar thuis in Nederland. Ik leef en werk dagelijks in beide culturen en talen. Voor u betekent dat: advies, offertes en communicatie in het Duits of Nederlands – zonder vertaalverlies en met écht begrip voor beide markten.",
      "In meer dan 20 jaar beroeps- en praktijkervaring heb ik beide kanten van de digitalisering leren kennen: de technische in IT en programmeren – en de ondernemerskant in commerciële functies. Daarbij komt jarenlange saleservaring, onder andere bij Telekom Deutschland, Vodafone en Postcon Deutschland. Ik weet dus niet alleen hoe software wordt gebouwd, maar ook hoe klanten denken, hoe processen in bedrijven écht lopen en waar projecten in de praktijk op stuklopen – precies dat inzicht vloeit in elk project.",
      "NeXify AI is het antwoord op een simpele observatie: de meeste digitale projecten zijn te duur, duren te lang en verliezen kwaliteit tussen de afdelingen van een bureau. Als ervaren ontwikkelaar en adviseur verenig ik concept, architectuur, uitvoering en kwaliteitscontrole in één hand.",
      "De modernste AI-tools – dezelfde die achter NeXify AI staan – versnellen onderzoek, code, tests en documentatie vele malen. Zo ontstaan in dagen resultaten waar klassieke processen maanden voor nodig hebben. De vakinhoudelijke verantwoordelijkheid blijft daarbij altijd persoonlijk bij mij.",
      "Ik werk vanuit Venlo voor bedrijven in Duitsland, Oostenrijk, Zwitserland en Nederland – in het Duits en Nederlands, uitsluitend B2B, altijd met een transparant dagtarief en schriftelijke scope-duidelijkheid vóór projectstart.",
    ],
    facts: [
      { label: "Afkomst", value: "Duitser · grensregio Limburg" },
      { label: "Locatie", value: "Venlo, Nederland (5+ jaar)" },
      { label: "Ervaring", value: "20+ jaar IT, commercie & sales" },
      { label: "Talen", value: "Duits, Nederlands, Engels" },
      { label: "Markt", value: "DE · AT · CH · NL" },
      { label: "Model", value: "B2B, € 999 netto/dag" },
    ],
    journeyTitle: "Ervaring die u merkt",
    journeyIntro: "Meer dan 20 jaar praktijk – technisch, commercieel en in sales. Die combinatie is zeldzaam en maakt het verschil tussen een website en een instrument dat verkoopt.",
    journey: [
      { title: "IT & ontwikkeling", text: "Ruim twee decennia praktijk in IT en programmeren – van solide systemen tot moderne AI-architecturen. Techniek is bij mij geen black box, maar vakmanschap met verantwoordelijkheid." },
      { title: "Commerciële praktijk", text: "Calculatie, processen, verantwoordelijkheid: ik heb zelf commercieel gewerkt en weet hoe beslissingen in bedrijven vallen – en wat een investering écht moet rechtvaardigen." },
      { title: "Sales op concernniveau", text: "Jarenlange saleservaring o.a. bij Telekom Deutschland, Vodafone en Postcon Deutschland. Ik begrijp doelgroepen, klantbehoeften en hoe van interesse meetbare omzet wordt." },
      { title: "Twee landen, één regio", text: "Als Duitser in Nederland, getrouwd met een Nederlandse, verbind ik beide zakelijke culturen – ideaal voor bedrijven in de Duits-Nederlandse economische regio." },
    ],
    principlesTitle: "Mijn werkprincipes",
    principles: [
      { title: "Eerlijkheid boven omzet", text: "Als een project niet zinvol is, zeg ik het – inclusief voordeligere alternatieven." },
      { title: "Resultaat boven inspanning", text: "Afgerekend wordt wat resultaten oplevert. Stilstand en vergadermarathons zijn niet uw probleem." },
      { title: "Eigendom bij de klant", text: "Code, data, toegangen en documentatie zijn van u. Volledig, vanaf dag één." },
      { title: "Gecontroleerde AI", text: "AI versnelt mijn werk, maar vervangt nooit controle, verantwoordelijkheid en goedkeuring door de vakman." },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Vertel mij over uw project",
    intro: "U ontvangt binnen één werkdag een persoonlijk, gekwalificeerd antwoord met een eerlijke inschatting en urenraming. Of laat u direct adviseren door de NeXify AI chat – 24/7.",
    name: "Uw naam *",
    email: "E-mailadres *",
    companyField: "Bedrijf",
    phone: "Telefoon (optioneel)",
    message: "Uw plan *",
    messagePlaceholder: "Wat wilt u realiseren? Website, shop, app, automatisering … Hoe concreter, hoe preciezer de inschatting.",
    submit: "Aanvraag versturen",
    sending: "Wordt verzonden …",
    success: "Hartelijk dank! Uw aanvraag is ontvangen – u krijgt zo een bevestiging per e-mail en binnen één werkdag een persoonlijk antwoord.",
    error: "Verzenden mislukt. Probeer het opnieuw of mail direct naar",
    directTitle: "Directe lijn",
    responseTitle: "Reactietijd",
    responseText: "Binnen één werkdag – meestal aanzienlijk sneller.",
    b2bNote: "Uitsluitend B2B: aanbiedingen richten zich op bedrijven, zelfstandigen en organisaties.",
  },
};
